# Generated by Django 3.1.7 on 2021-03-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route',
            new_name='segments',
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
