# Generated by Django 3.1.7 on 2021-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20210315_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
    ]
